<a href="https://colab.research.google.com/github/LBQTrung/NumPy/blob/main/numpy_exercises_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm này.

1. Cú pháp:

numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)

2. Ý nghĩa của từng tham số:

* func1d: Hàm này phải chấp nhận mảng một chiều. Nó được áp dụng cho các hàng hoặc cột của arr theo trục được chỉ định.

* axis: Xác định trục để arr được cắt.

* arr: Mảng đầu vào

* kwargs: Các đối số được đặt tên bổ sung cho func1d.

3. Hàm trả về: Một mảng có hình dạng giống mảng đầu vào, ngoại trừ giá trị theo các trục được thay thế bằng các giá trị mới bằng giá trị trả về của func1d.

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

Import thư viện Numpy: 

In [ ]:
import numpy as np

In [ ]:
A = np.random.randint(0,20, (15,17))
print(A)

[[ 8 18 10 19  5  4  8  8 13 14 16 19 10  8 17  0 10]
 [19  7 12 11 15 16 14  3 14  7  3 19  6 17  0  6  9]
 [16 11 18  2  0 11 10 14 16  9 16  8 14 14  4  8  8]
 [ 4  6  7  8  5  6 11  5 14  4 11 12  3  9  7  4  9]
 [11  8 16 10 19  8  8  8 17  5  5  9 14  3 19  8 15]
 [15  4 17 18  6 16 14 17 14  3 12  5 19 15  1  2 10]
 [ 9  7 16  8  3 11 18 10 11  9  2  2 14  3  0  9 14]
 [ 4  7  9  4 13  7 13  6 13 10 14  9  2  0  7 14 13]
 [ 2  7  2 10  0  6  5 18 17  2  4 10  6  1 15 17 16]
 [ 2 17  0 14 14  6  7 15 14  4  3  4 10  2 16 17  5]
 [13 13 13 13  9 10  6 14 11  6 11 13 16  0  3  5 10]
 [ 9 12  8 13 14 13 13 14 18 13  9 16  9 19  4 17  7]
 [ 1  6  9  7 13  6 10  5 12  6  5 11  7 17  2 17  8]
 [10  3  3 14  7  0 15  5  7  6  2 18  6  5  7  5  0]
 [ 6  8 17 15  6 14  9  1 19  1  3 10  4 16 11  0  4]]


Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tim_gia_tri_lon_nhat(vector_a):
  return np.max(vector_a)
print("Tập các giá trị lớn nhất của các hàng: \n",np.apply_along_axis(tim_gia_tri_lon_nhat, 1, A))


Tập các giá trị lớn nhất của các hàng: 
 [19 19 18 14 19 19 18 14 18 17 16 19 17 18 19]


Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tim_gia_tri_nho_nhat(vector_a):
  return np.min(vector_a)
print("Tập các giá trị nhỏ nhất của các cột: \n",np.apply_along_axis(tim_gia_tri_nho_nhat, 0, A))

Tập các giá trị nhỏ nhất của các cột: 
 [1 3 0 2 0 0 5 1 7 1 2 2 2 0 0 0 0]


Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tinh_tong(vector_a):
  return np.sum(vector_a)
print("Tập các tổng giá trị các hàng: \n",np.apply_along_axis(tinh_tong, 1, A))

Tập các tổng giá trị các hàng: 
 [187 178 179 125 183 188 146 145 138 150 166 208 142 113 144]


Câu 6: Xây dựng hàm tìm có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [ ]:
def tinh_tong_2(vector_a):
  s = 0
  for i in range(len(vector_a)):
    if (i % 2 != 0):
      s += vector_a[i]
  return s

print("Tập các tổng các giá trị có index lẻ của hàng: \n", np.apply_along_axis(tinh_tong_2, 1, A))

Tập các tổng các giá trị có index lẻ của hàng: 
 [ 90  86  77  54  59  80  59  57  71  79  74 117  75  56  65]
