<a href="https://colab.research.google.com/github/LBQTrung/NumPy/blob/main/numpy_exercises_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import thư viện numpy

In [1]:
import numpy as np

Bài 1: Xét không gian $R^3$, một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo giá trị của điểm A nêu trên bằng Numpy.

In [ ]:
a = np.array([5,7,14])
print(a)

[ 5  7 14]


Bài 2: Mở rộng không gian lên R15, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7,
8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print("Điểm A: ", a)

Điểm A:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3: Hãy viết chương trình sinh ngẫu nhiên một vector trong không gian Rn với n là số nguyên dương
được nhập vào từ bàn phím. Yêu cầu: sử dụng Numpy.

In [3]:
# Hàm kiểm tra dữ liệu nhập vào có phải là số dương hay không
def check_positve_integer(number):
  try:
    if (int(number) > 0):
      return True
    else:
      return False
  except:
    return False

# Hàm sinh ngẫu nhiên điểm, vector 
# input: số điểm cần sinh ngẫu nhiên
# output: list chứa các điểm
# Mục đích: Tái sử dụng cho các bài sau
def random_dot_vector(number):
  n = input("Nhập số nguyên dương: ")

  while not check_positve_integer(n):
    n = input("Nhập số nguyên dương: ")
  n = int(n)
  result = [np.random.randint(0,10,n) for i in range(number)]
  return result


In [ ]:
# Sinh ngẫu nhiên vector a
a = random_dot_vector(1)[0]
print(a)

Nhập số nguyên dương: 3
[4 4 4]


Bài 4: Hãy viết chương trình tính chiều dài của vector OA.

In [ ]:
#vector OA
a = np.array([7,-5,8])
# Chiều dài của vector OA
la = np.linalg.norm(a)
print(la)

11.74734012447073


Bài 5: Trong không gian Rn, hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector AB và tính chiều dài của vector này. Lưu ý: sử dụng Numpy.

In [ ]:
# Sinh ngẫu nhiên điểm A, B:
a,b = random_dot_vector(2)
print("Điểm A: ",a)
print("Điểm B: ",b)
#Vector AB
c = b - a
print("Vector AB là: ",c)

# Chiều dài vector AB
dist = np.linalg.norm(c)
print("Chiều dài vector AB là: ", dist)


Nhập số nguyên dương: 3
Điểm A:  [9 8 4]
Điểm B:  [6 9 6]
Vector AB là:  [-3  1  2]
Chiều dài vector AB là:  3.7416573867739413


Bài 6: Tích vô hướng của 2 vector

In [ ]:
# Sinh ngẫu nhiên 2 vector a,b
a,b = random_dot_vector(2)
print("Vector a: ",a)
print("Vector b: ",b)
# Tích vô hướng của 2 vector a, b:
c = np.inner(a,b)
print("Tích vô hướng là: ",c)

Nhập số nguyên dương: 3
Vector a:  [7 4 2]
Vector b:  [4 0 1]
Tích vô hướng là:  30


Bài 7: Tích hữu hướng (cross product) của 2 vector a

In [ ]:
# Sinh ngẫu nhiên 2 vector a,b
a,b = random_dot_vector(2)
print("Vector a: ",a)
print("Vector b: ",b)
# Tích hữu hướng của 2 vector a, b:
c = np.cross(a,b)
print("Tích hữu hướng là: ",c)

Nhập số nguyên dương: 3
Vector a:  [7 2 4]
Vector b:  [1 5 5]
Tích hữu hướng là:  [-10 -31  33]


Bài 8: Hãy viết chương trình sinh ngẫu nhiên một vector a trong không gian Rn, số nguyên dương n được nhập vào từ bàn phím. Xuất ra màn hình giá của vector a và chuyển vị của vector a

In [5]:
# Sinh ngẫu nhiên vector a
a = random_dot_vector(1)[0]
print("Vector a: ",a)
print("Chuyển vị của vector a: \n",a.reshape(len(a),1))

Nhập số nguyên dương: 3
Vector a:  [4 4 3]
Chuyển vị của vector a: 
 [[4]
 [4]
 [3]]


Bài 9: Hãy:
* Xuất a và b ra màn hình
* Tạo vector tương ứng từ a và b, xuất kết quả ra màn hình
* Thực hiện phép chuyển vị đối với 2 vector ở trên và xuất kết quả ra màn hình.

In [ ]:
a = [1,2,3,4,5]
b = [[1],[2],[3],[4],[5]]
# Xuất a, b ra màn hình
print("List a: ",a)
print("List b: ",b)

# Tạo vector tương ứng và xuất ra màn hình
v_a = np.array(a)
v_b = np.array(b)
print("Vector a: ",v_a)
print("Vector b: \n",v_b)

# Chuyển vị 2 vector và xuất ra màn hình
print("Vector chuyển vị của a: ",v_a.T)
print("Vector chuyển vị của b: ",v_b.T)

List a:  [1, 2, 3, 4, 5]
List b:  [[1], [2], [3], [4], [5]]
Vector a:  [1 2 3 4 5]
Vector b: 
 [[1]
 [2]
 [3]
 [4]
 [5]]
Vector chuyển vị của a:  [1 2 3 4 5]
Vector chuyển vị của b:  [[1 2 3 4 5]]


Bài 10: Sinh ngẫu nhiên hai vector a, b
* Thực hiện phép nhân: ma với a là vector, m là số bất kì và xuất kết quả ra màn hình
* Thực hiện phép cộng 2 vector a + b và xuất kết quả ra màn hình

In [ ]:
# Sinh ngẫu nhiên 2 vector a,b
a,b = random_dot_vector(2)
print("Vector a: ",a)
print("Vector b: ",b)

m = float(input("Nhập số muốn nhân với vector a: "))
print(f"a * {m} = ",a * m)

print("a + b = ", a + b)

Nhập số nguyên dương: 3
Vector a:  [7 4 9]
Vector b:  [6 9 9]
Nhập số muốn nhân với vector a: 5
a * 5.0 =  [35. 20. 45.]
a + b =  [13 13 18]
