<a href="https://colab.research.google.com/github/LBQTrung/NumPy/blob/main/numpy_exercises_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import thư viện Numpy:

In [1]:
import numpy as np

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

Tạo hàm ghi chú:

In [3]:
def note(vector_a):
  print("Vector a: ",vector_a)
  print("Số chiều của vector a: ", vector_a.size)
  print("Kích thước của vector_a: ", vector_a.shape)
  print()
  print("Vector chuyển vị của a: \n", vector_a.reshape(7,1))
  print("Số chiều của vector chuyển vị của a: ", (vector_a.reshape(len(vector_a),1)).size)
  print("Kích thước của chuyển vị của  vector_a: ", vector_a.reshape(len(vector_a),1).shape)

* np.arange():

In [4]:
vector_a = np.arange(0,7,1)
note(vector_a)

Vector a:  [0 1 2 3 4 5 6]
Số chiều của vector a:  7
Kích thước của vector_a:  (7,)

Vector chuyển vị của a: 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Số chiều của vector chuyển vị của a:  7
Kích thước của chuyển vị của  vector_a:  (7, 1)


* np.linspace():

In [5]:
vector_a = np.linspace(0,10,num = 7)
note(vector_a)


Vector a:  [ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]
Số chiều của vector a:  7
Kích thước của vector_a:  (7,)

Vector chuyển vị của a: 
 [[ 0.        ]
 [ 1.66666667]
 [ 3.33333333]
 [ 5.        ]
 [ 6.66666667]
 [ 8.33333333]
 [10.        ]]
Số chiều của vector chuyển vị của a:  7
Kích thước của chuyển vị của  vector_a:  (7, 1)


* np.logspace():

In [6]:
vector_a = np.logspace(1,2, num = 7)
note(vector_a)

Vector a:  [ 10.          14.67799268  21.5443469   31.6227766   46.41588834
  68.12920691 100.        ]
Số chiều của vector a:  7
Kích thước của vector_a:  (7,)

Vector chuyển vị của a: 
 [[ 10.        ]
 [ 14.67799268]
 [ 21.5443469 ]
 [ 31.6227766 ]
 [ 46.41588834]
 [ 68.12920691]
 [100.        ]]
Số chiều của vector chuyển vị của a:  7
Kích thước của chuyển vị của  vector_a:  (7, 1)


* np.random.rand():

In [7]:
vector_a = np.random.rand(7)
note(vector_a)

Vector a:  [0.51297983 0.54809721 0.00471024 0.42342072 0.78923386 0.31267869
 0.4617374 ]
Số chiều của vector a:  7
Kích thước của vector_a:  (7,)

Vector chuyển vị của a: 
 [[0.51297983]
 [0.54809721]
 [0.00471024]
 [0.42342072]
 [0.78923386]
 [0.31267869]
 [0.4617374 ]]
Số chiều của vector chuyển vị của a:  7
Kích thước của chuyển vị của  vector_a:  (7, 1)


Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận A10x7 với giá trị các phần tử của ma trận A
được sinh bởi:
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

* Tạo hàm xuất kết quả:

In [ ]:
def output_result(matrix_A):
  print("Ma trận A: \n", matrix_A)
  print("Số chiều của A: ", matrix_A.ndim)
  print("Kích thước của A: ", matrix_A.shape)
  print()
  print("Ma trận chuyển vị của A: \n", matrix_A.T)
  print("Số chiều của chuyển vị của A: ", (matrix_A.T).ndim)
  print("Kích thước của chuyển vị của A: ", (matrix_A.T).shape)

* np.arrange()

In [ ]:
matrix_A = np.arange(0,70,1).reshape(10,7)
output_result(matrix_A)

Ma trận A: 
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
Số chiều của A:  2
Kích thước của A:  (10, 7)

Ma trận chuyển vị của A: 
 [[ 0  7 14 21 28 35 42 49 56 63]
 [ 1  8 15 22 29 36 43 50 57 64]
 [ 2  9 16 23 30 37 44 51 58 65]
 [ 3 10 17 24 31 38 45 52 59 66]
 [ 4 11 18 25 32 39 46 53 60 67]
 [ 5 12 19 26 33 40 47 54 61 68]
 [ 6 13 20 27 34 41 48 55 62 69]]
Số chiều của chuyển vị của A:  2
Kích thước của chuyển vị của A:  (7, 10)


* np.linspace():

In [ ]:
matrix_A = np.linspace((1,1,1,1,1,1,1),(100,100,100,100,100,100,100),10)
output_result(matrix_A)

Ma trận A: 
 [[  1.   1.   1.   1.   1.   1.   1.]
 [ 12.  12.  12.  12.  12.  12.  12.]
 [ 23.  23.  23.  23.  23.  23.  23.]
 [ 34.  34.  34.  34.  34.  34.  34.]
 [ 45.  45.  45.  45.  45.  45.  45.]
 [ 56.  56.  56.  56.  56.  56.  56.]
 [ 67.  67.  67.  67.  67.  67.  67.]
 [ 78.  78.  78.  78.  78.  78.  78.]
 [ 89.  89.  89.  89.  89.  89.  89.]
 [100. 100. 100. 100. 100. 100. 100.]]
Số chiều của A:  2
Kích thước của A:  (10, 7)

Ma trận chuyển vị của A: 
 [[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]]
Số chiều của chuyển vị của A:  2
Kích thước của chuyển vị của A:  (7, 10)


* np.logspace():

In [ ]:
matrix_A = np.logspace((1,1,1,1,1,1,1),(3,3,3,3,3,3,3),10)
output_result(matrix_A)

Ma trận A: 
 [[  10.           10.           10.           10.           10.
    10.           10.        ]
 [  16.68100537   16.68100537   16.68100537   16.68100537   16.68100537
    16.68100537   16.68100537]
 [  27.82559402   27.82559402   27.82559402   27.82559402   27.82559402
    27.82559402   27.82559402]
 [  46.41588834   46.41588834   46.41588834   46.41588834   46.41588834
    46.41588834   46.41588834]
 [  77.42636827   77.42636827   77.42636827   77.42636827   77.42636827
    77.42636827   77.42636827]
 [ 129.1549665   129.1549665   129.1549665   129.1549665   129.1549665
   129.1549665   129.1549665 ]
 [ 215.443469    215.443469    215.443469    215.443469    215.443469
   215.443469    215.443469  ]
 [ 359.38136638  359.38136638  359.38136638  359.38136638  359.38136638
   359.38136638  359.38136638]
 [ 599.48425032  599.48425032  599.48425032  599.48425032  599.48425032
   599.48425032  599.48425032]
 [1000.         1000.         1000.         1000.         1000.
  1000.

* np.random.rand():



In [ ]:
matrix_A = np.random.rand(10,7)
output_result(matrix_A)

Ma trận A: 
 [[0.85665165 0.33292284 0.85783392 0.7147777  0.1799201  0.43435635
  0.54119006]
 [0.40356866 0.63512268 0.47896718 0.06379604 0.0013522  0.0680864
  0.06315829]
 [0.89953329 0.1607472  0.73569835 0.2773898  0.72416393 0.98008893
  0.59890158]
 [0.31712494 0.36788132 0.83047616 0.5463873  0.48034846 0.35214833
  0.40610528]
 [0.99899546 0.587354   0.4629964  0.09831111 0.83536506 0.29534804
  0.91996561]
 [0.08678592 0.48928523 0.20069851 0.47705411 0.50307849 0.79221735
  0.28762326]
 [0.2278749  0.89859231 0.99382112 0.41431723 0.93210762 0.06071208
  0.8777719 ]
 [0.80046415 0.35953994 0.85620601 0.36965418 0.18996341 0.57347418
  0.04302332]
 [0.83640105 0.41556592 0.02063461 0.45283453 0.27656851 0.2085322
  0.61011161]
 [0.40457751 0.86660242 0.44377594 0.559653   0.60297692 0.21651696
  0.01680578]]
Số chiều của A:  2
Kích thước của A:  (10, 7)

Ma trận chuyển vị của A: 
 [[0.85665165 0.40356866 0.89953329 0.31712494 0.99899546 0.08678592
  0.2278749  0.80046415 0.

Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())

In [ ]:
matrix_A = np.arange(0,70,1).reshape(10,7)
vector_a = matrix_A.flatten()
print(vector_a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [ ]:
matrix_B = vector_a.reshape(10,7)
print(matrix_B)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]


Câu 4:Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();

In [ ]:
matrix_A = np.logspace(0,3,150).reshape(10,15)
print(matrix_A)

[[   1.            1.04745224    1.09715619    1.1492187     1.2037517
     1.26087241    1.32070362    1.38337396    1.44901815    1.5177773
     1.58979923    1.66523876    1.74425806    1.827027      1.91372352]
 [   2.00453398    2.0996536     2.19928686    2.30364794    2.41296118
     2.52746159    2.64739529    2.77302012    2.90460612    3.04243618
     3.18680658    3.33802767    3.49642455    3.66233771    3.83612383]
 [   4.01815648    4.20882699    4.40854524    4.61774057    4.83686269
     5.06638264    5.30679382    5.55861305    5.82238167    6.0986667
     6.38806207    6.6911899     7.00870182    7.3412804     7.68964057]
 [   8.05453121    8.43673672    8.83707874    9.25641789    9.69565562
    10.15573615   10.63764854   11.14242875   11.67116191   12.22498464
    12.8050875    13.41271753   14.04918097   14.71584602   15.41414582]
 [  16.1455815    16.91172545   17.71422463   18.5548042    19.43527115
    20.35751822   21.32352798   22.33537706   23.39524065   24.

- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);

In [ ]:
row_vector = matrix_A[2, :] 
print(row_vector)

[4.01815648 4.20882699 4.40854524 4.61774057 4.83686269 5.06638264
 5.30679382 5.55861305 5.82238167 6.0986667  6.38806207 6.6911899
 7.00870182 7.3412804  7.68964057]


- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [ ]:
col_vector = matrix_A[:, 4]
print(col_vector)

[  1.2037517    2.41296118   4.83686269   9.69565562  19.43527115
  38.95866145  78.09396072 156.54199797 313.79375437 629.01024362]


Câu 5: Thực hiện các yêu cầu sau:

- Xây dựng hàm tính giá trị trung bình:

In [ ]:
def calculate_mean(vector_a):
  s = 0
  for i in vector_a:
    s += i
  return s/len(vector_a)

- Xây dựng hàm tính giá trị trung vị:

In [ ]:
def calculate_median(vector_a):
  len_a = len(vector_a)
  # Sắp xếp các phần từ theo giá trị tăng dần:
  for i in range(len_a - 1):
    for j in range(i + 1, len_a):
      if (vector_a[i] > vector_a[j]):
        vector_a[i],vector_a[j] = vector_a[j], vector_a[i]
  
  # Tìm trung vị:
  if (len_a % 2 != 0):
    return vector_a[int(len_a / 2)]
  else:
    return ((vector_a[int((len_a-1)/2)]) + (vector_a[int((len_a-1)/2) + 1])) / 2

- Xây dựng hàm tính giá trị yếu vị:

In [ ]:
def calculate_mode(vector_a):
    result = []
    # Tần số của các phần từ trong vector_a:
    freq_dict = {}
    for i in vector_a:
        if i in freq_dict:
            freq_dict[i] += 1
        else:
            freq_dict[i] = 1
    
    # Tìm tần số lớn nhất:
    max_freq = 0
    for i in freq_dict.values():
        if i >= max_freq:
            max_freq = i
    
    # Tìm số yếu vị:
    for i in freq_dict:
        if freq_dict[i] == max_freq:
            result.append(i)
    return result

- Xây dựng hàm tính phương sai:

In [ ]:
def calculate_variance(vector_a):
  mean_a = calculate_mean(vector_a)
  s = 0
  for i in vector_a:
    s += (i - mean_a) ** 2
  return s/(len(vector_a))

- Xây dựng hàm tính độ lệch chuẩn:

In [ ]:
def calculate_sd(vector_a):
  return calculate_variance(vector_a) ** 0.5

- Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arrange():

In [ ]:
A = np.arange(1,151,1).reshape(15,10)
print(A)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]


- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A

Trung bình:

In [ ]:
np.apply_along_axis(calculate_mean, 1, A)

array([  5.5,  15.5,  25.5,  35.5,  45.5,  55.5,  65.5,  75.5,  85.5,
        95.5, 105.5, 115.5, 125.5, 135.5, 145.5])

Trung vị:

In [ ]:
np.apply_along_axis(calculate_median, 1, A)

array([  5.5,  15.5,  25.5,  35.5,  45.5,  55.5,  65.5,  75.5,  85.5,
        95.5, 105.5, 115.5, 125.5, 135.5, 145.5])

Yếu vị:

In [ ]:
np.apply_along_axis(calculate_mode, 1, A)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]])

Phương sai:

In [ ]:
np.apply_along_axis(calculate_variance, 1, A)

array([8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25,
       8.25, 8.25, 8.25, 8.25])

Độ lệch chuẩn:

In [ ]:
np.apply_along_axis(calculate_sd, 1, A)

array([2.87228132, 2.87228132, 2.87228132, 2.87228132, 2.87228132,
       2.87228132, 2.87228132, 2.87228132, 2.87228132, 2.87228132,
       2.87228132, 2.87228132, 2.87228132, 2.87228132, 2.87228132])

- Áp dụng 5 hàm ở trên cho từng cột của ma trận A:

Trung bình:

In [ ]:
np.apply_along_axis(calculate_mean, 0, A)

array([71., 72., 73., 74., 75., 76., 77., 78., 79., 80.])

Trung vị:

In [ ]:
np.apply_along_axis(calculate_median, 0, A)

array([71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

Yếu vị:

In [ ]:
np.apply_along_axis(calculate_mode, 0, A)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]])

Phương sai:

In [ ]:
np.apply_along_axis(calculate_variance, 0, A)

array([1866.66666667, 1866.66666667, 1866.66666667, 1866.66666667,
       1866.66666667, 1866.66666667, 1866.66666667, 1866.66666667,
       1866.66666667, 1866.66666667])

Độ lệch chuẩn:

In [ ]:
np.apply_along_axis(calculate_sd, 0, A)

array([43.20493799, 43.20493799, 43.20493799, 43.20493799, 43.20493799,
       43.20493799, 43.20493799, 43.20493799, 43.20493799, 43.20493799])